export const skillList: string[] = [
  'a + b',
  'b + a',
  'a - b',
  'b - a',
  'a + b + b',
  'b + a + a',
  'a - b - b',
  'b - a - a',
  'a * b',
  'b * a',
  'a * b - 3',
  'b * a - 3',
  'a + 3',
  'b + 3',
  'a / -2 | 0',
  'b / -2 | 0',
  'a * -2',
  'b * -2',
  'a - b + 3',
  'b - a + 3',
  'a / b | 0',
  'b / a | 0',
  'b * b - a',
  'a * a - b',
  'a * a / b | 0',
  'b * b / a | 0',
  'a * a - b - b',
  'b * b - a - a',
  'a / b | 0 - b',
  'b / a | 0 - a',
  'b + a / b | 0',
  'a + b / a | 0',
];